== ShellScript?

	shell is a interpreter which is used to run your commands.

=== automation:
	perl, python, yaml,shell
interpreter and compiler


=== Session 3

	==== shell scripting?

	shell script file:-			
		filename.sh
		/bin/bash
			#!-> shebang			#!/bin/bash
			
	
	For comments 
		- single line comment use "#" 
			"# this is commented text"
		- multi line comment use ">> <LABEL-NAME>

			<all the lines here would be commented.. till the label found.

			<LABEL-NAME> 

		Example : 

			>> comment-start
			echo "test"
			echo "come to home "
			comment-start 

			Now here all the lines from "comment-start" label to "comment-start"

			

	echo -e " special character with text"

	\n new line
	\t tab space
	\b  back space (\b after should containsome text) 
	\a  bell sound
	\v verical tab


	To know the command Location
	  which <comand-name>
	  /bin  --> Location

	To print value of a variable 
	echo $PATH 

	To Create Custom Command / User Defined Command.

	Create a file and give chmod 700 to that file 
	and the directory in which you have created that file should be added into the environment variable path.


	chmod u+x <filename>

	ll <file-name>

	echo $PATH 
	/sbin:/bin:/usr/bin:/user/sbin

	Now suppose the newly created file is in root directory then add the root directory in the PATH 
	export PATH = /sbin:/bin:/usr/bin:/user/sbin:/root 





	echo $SHELL --> Will print the current used SHELL 
	if you want to switch the SHELL then just type "ksh" to switch to K shell.

	To switch to Bash Shell -->type "bash" 

    To know the installed Shell
	ps -p $$ 


	To create a Shell script. The file name would be with ".sh" extension (optinal).

	And the very first line would be 
	#!/bin/bash

	To ensure that when the file is executed, it will run in bash shell and if bash shell is not installed
	 then it would flag the error on very first line.
 
	In vi editor, press "i" to enable insert mode.

	once done with the editing, press ESC to exit from the INSERT MODE, and then press colon(:).
	After colon press "wq" for save the write and quit OR "q" for quite without saving the changes.

	":wq" + ENTER -> Save and quit
	":q" + ENTER  -> Quit without saving the content

	Once file is saved, you can view the content with cat command 
	cat <file-name>
	cat -n <file-name>  ("-n" flag to see line numbers as well)

	To execute the shellscript file 
	sh <file-name>.sh (Can run globally)

	OR 

	. <file-name>.sh  (Only if you are in the same directory)

	sh display.sh OR . display.sh 
	
	OR 

	./<file-name>.sh (File should have executable permission )


	OR

	bash -x <file-name>.sh (Run the file in a debug mode)



=== Session 4

>>About the echo command
			>> colors
			>> -e option
>>Vares (how to define and how to access them)
	x  = 2 + y
	if y= 1
	x = 2 + 1
	x = 3


echo $? 
if it returns 0 then the previous command or script executed successfully
otherwise 0 then it is not successfully executed. 

variable  key points:
--------------------?
--> variable name should be a-z , A-Z , 0-9 and special character _

--> you should not start the varibale name with number
-->doint include spaces in the variable name(if is required to use _(underscore).
-->***** dont take the variable as the command name.
---> variable names are case sensitive

>> Rules for defining the variables
>> Bash initilization ***



Sample Bash Files 
1. 
#!/bin/bash 
echo "Enter First Number"
read a 
echo "Enter Second Number"
read b 
c=`expr $a + $b`
echo $c;


2. 
#!/bin/bash 
read -p "Enter First Value" a 
read -p "Enter Second Value" b 
c=`expr $a + $b`
echo $c;

Points:
`expr $a + $b` - With space it will add and give result 
`expr $a+$b` - Without space it will concatenate values  
`expr $a \* $b` - For multiply we need to add escaping as "*" is reserved value in Linux 




=== Resources

	https://www.shellscript.sh/

	Online Linxu Terminals to Practice LINUX :
	https://bellard.org/jslinux/
	https://itsfoss.com/online-linux-terminals/			
	https://linuxzoo.net/page/centos_basic1.html				



