== ShellScript?

	shell is a interpreter which is used to run your commands.

=== automation:
	perl, python, yaml,shell
interpreter and compiler


=== Session 3

	==== shell scripting?

	shell script file:-			
		filename.sh
		/bin/bash
			#!-> shebang			#!/bin/bash
			
	
	For comments 
		- single line comment use "#" 
			"# this is commented text"
		- multi line comment use ">> <LABEL-NAME>

			<all the lines here would be commented.. till the label found.

			<LABEL-NAME> 

		Example : 

			>> comment-start
			echo "test"
			echo "come to home "
			comment-start 

			Now here all the lines from "comment-start" label to "comment-start"

			

	echo -e " special character with text"

	\n new line
	\t tab space
	\b  back space (\b after should containsome text) 
	\a  bell sound
	\v verical tab


	To know the command Location
	  which <comand-name>
	  /bin  --> Location

	To print value of a variable 
	echo $PATH 

	To Create Custom Command / User Defined Command.

	Create a file and give chmod 700 to that file 
	and the directory in which you have created that file should be added into the environment variable path.


	chmod u+x <filename>

	ll <file-name>

	echo $PATH 
	/sbin:/bin:/usr/bin:/user/sbin

	Now suppose the newly created file is in root directory then add the root directory in the PATH 
	export PATH = /sbin:/bin:/usr/bin:/user/sbin:/root 





	echo $SHELL --> Will print the current used SHELL 
	if you want to switch the SHELL then just type "ksh" to switch to K shell.

	To switch to Bash Shell -->type "bash" 

    To know the installed Shell
	ps -p $$ 


	To create a Shell script. The file name would be with ".sh" extension (optinal).

	And the very first line would be 
	#!/bin/bash

	To ensure that when the file is executed, it will run in bash shell and if bash shell is not installed
	 then it would flag the error on very first line.
 
	In vi editor, press "i" to enable insert mode.

	once done with the editing, press ESC to exit from the INSERT MODE, and then press colon(:).
	After colon press "wq" for save the write and quit OR "q" for quite without saving the changes.

	":wq" + ENTER -> Save and quit
	":q" + ENTER  -> Quit without saving the content

	Once file is saved, you can view the content with cat command 
	cat <file-name>
	cat -n <file-name>  ("-n" flag to see line numbers as well)

	To execute the shellscript file 
	sh <file-name>.sh (Can run globally)

	OR 

	. <file-name>.sh  (Only if you are in the same directory)

	sh display.sh OR . display.sh 
	
	OR 

	./<file-name>.sh (File should have executable permission )


	OR

	bash -x <file-name>.sh (Run the file in a debug mode)



=== Session 4

>>About the echo command
			>> colors
			>> -e option
>>Vares (how to define and how to access them)
	x  = 2 + y
	if y= 1
	x = 2 + 1
	x = 3


echo $? 
if it returns 0 then the previous command or script executed successfully
otherwise 0 then it is not successfully executed. 

variable  key points:
--------------------?
--> variable name should be a-z , A-Z , 0-9 and special character _

--> you should not start the varibale name with number
-->doint include spaces in the variable name(if is required to use _(underscore).
-->***** dont take the variable as the command name.
---> variable names are case sensitive

>> Rules for defining the variables
>> Bash initilization ***



Sample Bash Files 
1. 
#!/bin/bash 
echo "Enter First Number"
read a 
echo "Enter Second Number"
read b 
c=`expr $a + $b`
echo $c;


2. 
#!/bin/bash 
read -p "Enter First Value" a 
read -p "Enter Second Value" b 
c=`expr $a + $b`
echo $c;

Points:
`expr $a + $b` - With space it will add and give result 
`expr $a+$b` - Without space it will concatenate values  
`expr $a \* $b` - For multiply we need to add escaping as "*" is reserved value in Linux 




==== Sessoion 7 

===== Conditional 
	a) if ..fi
			if [ condition]
			then
				statements;;;;;;;
			fi

	b) if ...else...if

			if [ conditon is true ]
			then
				stat:1
			else
				stat:2
			fi

	c) if....elif...elif...elif...else..if
			if [ cond1 ]
			then
				statement1
			elif [ cond2 ]
			then
				statements2
			elif [ cond3 ]
			then
				statement3
			..
			..
			else
				statements
			fi	

	d) case  $variable_name in 
			pattern_1)
					statement
					;;
			pattern_2) 
					statement
					;;
			*) 
				default statement
				;;
		esac 		

Note : ";;" is necessary 



Example :
	#!/bin/bash 
    read -p "Please enter your age" name 
    if [ $name -eq 10 ]
    then
        echo "You are selected as your Age is 10."
    fi 

    echo "I am outside the loop"
    

Example : 
#!/bin/bash 
if [ -e new.txt ]; then echo "File present"; else echo "Not
Present"; fi


Example : 
#!/bin/bash 
echo "Welcome to the cafeteria"
echo "=================================="
echo "Please make your choice from the menu give below:"
echo -e  "1. Tea\n2. Coffee\n3.Cold Drink"
read i
case $i in
1) echo "Tea Selected"
	;;
2) echo "Coffee Selected"
	;;
3) echo "Cold Drink Selected"
	;;
*) echo "Sorry we do not serve this Item"
	;;
esac
echo "Thank you for visiting Us!!"


====== Conditional Testing Operators 

	====== Numberic Testing Operators 
		-gt  Greater Than 
		-lt  Less Than 
		-le  Less Than Equal 
		-ge  Greater Than Equal 
		-ne  Not Equal 
		-eq  Equal 


	====== String Testing Operators 
		==  Equal To 
		!=  Not Equal To 
		-z  String Length Zero 
		-n  NonZero Length 


	====== File Based Testing Operators 
		-e <file-name>  To check if file exists
		-f <file-name>  Is it a regular file 
		-d <file-name>  Is it a Directory 
		-r <file-name>  Is it Readable
		-w <file-name>  Is it Writable
		-x <file-name>  Is it Executable
		-z <file-name>  Is it Zero Length 
		-s <file-name>  Is it Non Zero Length  
		

==== To pass the variables from command line to the file.
	sh abc.sh 10 20 30 40 
	In File, we can refer those variables using $0 $1 $2 $3 and so on.
	$0 is the file name "abc.sh"
	$1 is 10 and so on 


===== GREP Command Details 

Options Description
-c : This prints only a count of the lines that match a pattern
-h : Display the matched lines, but do not display the filenames.
-i : Ignores, case for matching
-l : Displays list of a filenames only.
-n : Display the matched lines and their line numbers.
-v : This prints out all the lines that do not matches the pattern
-e exp : Specifies expression with this option. Can use multiple times.
-f file : Takes patterns from file, one per line.
-E : Treats pattern as an extended regular expression (ERE)
-w : Match whole word
-o : Print only the matched parts of a matching line,
 with each such part on a separate output line.

------------------------------------------------------------
grep command in Unix/Linux
The grep filter searches a file for 
a particular pattern of characters, 
and displays all lines that contain that pattern. 
The pattern that is searched 
in the file is referred to as the 
regular expression (grep stands for globally 
search for regular expression and print out).


yntax:

grep [options] pattern [files]
Options Description
-c : This prints only a count of the lines that match a pattern
-h : Display the matched lines, but do not display the filenames.
-i : Ignores, case for matching
-l : Displays list of a filenames only.
-n : Display the matched lines and their line numbers.
-v : This prints out all the lines that do not matches the pattern
-e exp : Specifies expression with this option. Can use multiple times.
-f file : Takes patterns from file, one per line.
-E : Treats pattern as an extended regular expression (ERE)
-w : Match whole word
-o : Print only the matched parts of a matching line,
 with each such part on a separate output line.
----------------------------------------------------------

$cat > geekfile.txt
unix is great os. unix is opensource. unix is free os.
learn operating system.
Unix linux which one you choose.
uNix is easy to learn.unix is a multiuser os.Learn unix .unix is a powerful.
------------------------------------------------------------------------
1. Case insensitive search : 
The -i option enables to search for a string case insensitively in the give file. 
It matches the words like “UNIX”, “Unix”, “unix”.

$grep -i "UNix" geekfile.txt
------------------------------------------------------------------------


2. Displaying the count of number of matches : 
We can find the number of lines that matches the given string/pattern

$ grep -c "unix" geekfile.txt

------------------------------------------------------------------------
3. Display the file names that matches the pattern : 
We can just display the files that contains the given string/pattern.

$grep -l "unix" *

or
 
$grep -l "unix" f1.txt f2.txt f3.xt f4.txt
Output:


-----------------------------------------------------------------------

4. Checking for the whole words in a file : 
By default, grep matches the given string/pattern even if it found as a substring
 in a file. The -w option to grep makes it match only the whole words.

$ grep -w "unix" geekfile.txt
Output:

$ grep -w "uni" geekfile.txt ( you will no o/p)

------------------------------------------------------------------------
5. Displaying only the matched pattern : 
By default, grep displays the entire line which has the matched string. 
We can make the grep to display only the matched string by using the -o option.

$ grep -o "unix" geekfile.txt
Output:

------------------------------------------------------------------------
6. Show line number while displaying the output using grep -n :
 To show the line number of file with the line matched.

$ grep -n "unix" geekfile.txt
Output:

------------------------------------------------------------------------
7. Inverting the pattern match : You can display the lines that are not matched
 with the specified search sting pattern using the -v option.

$ grep -v "unix" geekfile.txt
Output:

------------------------------------------------------------------------
8. Matching the lines that start with a string : 
The ^ regular expression pattern specifies the start of a line. 
This can be used in grep to match the lines which start with the given string or pattern.

$ grep "^unix" geekfile.txt
Output:

------------------------------------------------------------------------

9. Matching the lines that end with a string : 
The $ regular expression pattern specifies the end of a line. 
This can be used in grep to match the lines which end with the given string or pattern.

$ grep "os$" geekfile.txt
------------------------------------------------------------------------
10.Specifies expression with -e option. Can use multiple times :

$grep –e "Agarwal" –e "Aggarwal" –e "Agrawal" geekfile.txt
------------------------------------------------------------------------

11. -f file option Takes patterns from file, one per line.

$cat pattern.txt

Agarwal
Aggarwal

Agrawal

$ grep –f pattern.txt  geekfile.txt




=== Loops 
Loop Types :
==== for loop

for VAR_NAME in <list>
do
	<STATEMENT TO EXECUTE>
done 

Example: for1.sh 

	#!/bin/sh
	# This is sample for loop example
	for i in 1 2 3 4 5 6 7 8 9 10
	do
			echo "Hello $i time"
			sleep 1
	done

for i in {1..10} //Run from 1 to 10 with +1 increment 
for i in {1..10..2} //Run from 1 to 10 with +2 increment 
	
==== Seq 
seq 2 20  //Run the loop from 2 to 20 with +1 increment 
seq 2 2 20//Run the loop from 2 to 20 with +2 increment  	

x = `seq 1 10`
echo $x // 1 2 3 4 5 6 7 8 9 10

for v in $(seq 1 10)
do
	echo $v 
done 

TASK : 
Write a program which take input of "directory name" and then it should output all the files/directory listed in it 

#!/bin/bash 
# File/Directory Exists or not
read -p "Please enter directory name: " n
ls $n 1>/dev/null 2>&1 
output=$?
if [ $output -eq 0 ]
then
        for v in $(ls $n)
        do
                echo "File /Directory name : $v"
        done
else
        echo "Invalid Directory Entered"
fi


$? is used to find the return value of the last executed command. 


Same thing in above scenario, we can also check the file type.
For conditional details, kindly refer session 06-07, where we have the list of possible 
condition evaluators.


 if [ -f $path/$var ]
 then
	echo "The File name is $path"/"$var";
 fi 

For Directory check:
if [ -d $path/$var ]
 then
	echo "The Directory name is $path"/"$var";
 fi 



==== while loop 
SYNTAX:
while (condition)/read
do
		exe.
done

while (conditon)
do
done < Input from file 

Example1:
#!/bin/bash 
read -p "Enter the number you want to print" var 
var2 = 1
while [ $var -le $var]
do
	echo $var2
	var2 = $((var2+1))
done 


Example2:
File: abc 
-------------
date
time 
ls

File: test.sh
--------------
#!/bin/bash 
while read val 
do
	echo $val
done < abc 

*Here "abc" is the file name that has some text. We are redirecting the ouput of the 
file and injecting it into the WHILE loop.
In above example while loop will read each line in each iteration 


Example3:
File: abc 
-------------
date time 
whoami cal 

File: test.sh
--------------
#!/bin/bash 
while read val 
do
	echo $val
done < abc 

OUTPUT:
-----------
Error - Because while reading each line "date time" is not a valid command 

To resolve that we need to pass more parameters that we want to read 

Example4:
File: abc 
-------------
date time ls  
whoami cal pwd

File: test.sh
--------------
#!/bin/bash 
while read val1 val2 val3  
do
	echo $val
	echo $val2 
	echo $val3 
done < abc 

Now val1 will have first value 
val2 will have second value And
val3 will have all the remaining values.

IFS - Internal Field separator 

EXAMPLE:
#!/bin/bash 
x=$IFS 
while IFS="," read a b c 
do 
	echo $a 
done < abc 
IFS=$x //Assigning back the value





==== until loop 


==== select loop 





=== Resources

	https://www.shellscript.sh/

	Online Linxu Terminals to Practice LINUX :
	https://bellard.org/jslinux/
	https://itsfoss.com/online-linux-terminals/			
	https://linuxzoo.net/page/centos_basic1.html				
	https://drive.google.com/drive/folders/199SOg_qYmYNU9dfpwooM4U47rnUom66c


